import '@/styles/globals.scss';
import type { AppProps } from 'next/dist/shared/lib/router/router';
import layout from '@/styles/layout.module.scss';
import Head from 'next/head';
import Header from '@/components/header';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={layout.container}>
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </>
  );
}
