import '@/styles/globals.scss';
import layout from '@/styles/layout.module.scss';
import Head from 'next/head';
import Menu from '@/components/menu/menu';
import Header from '@/components/header';

export default function App({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className={layout.container}>
				<Menu />
				<main>
					<Component {...pageProps} />
				</main>
			</div>
		</>
	);
}
